#!/usr/bin/env python

import sys
import requests

from twisted.python import log
from twisted.internet import reactor, protocol, task
from twisted.words.protocols import irc

class StravaClub(object):
    def __init__(self, club_id, access_token, update_interval):
        self.club_id = club_id
        self.access_token = access_token
        self.update_interval = update_interval

        self.callback = lambda x: None
        self.activities_seen = set()

    def start(self):
        self.update(initial=True)

        l = task.LoopingCall(self.update)
        l.start(self.update_interval, now=False)

    def update(self, initial=False):
        log.msg("Updating data")

        # Prevent spam and also deleting an activity revealing the 201st entry
        per_page = 200 if initial else 10

        r = requests.get(
            'https://www.strava.com/api/v3/clubs/%s/activities' % self.club_id,
            params={
                'per_page': per_page,
                'access_token': self.access_token,
            },
        )

        r.raise_for_status()

        size = len(self.activities_seen)

        for x in reversed(r.json()):
            if not initial and x['id'] not in self.activities_seen:
                self.callback(x)

            self.activities_seen.add(x['id'])

        log.msg("%d new activities found" % (len(self.activities_seen) - size))

class LogBot(irc.IRCClient):
    TEMPLATE = """
        %(athlete)s (%(type)s): %(name)s (%(distance_km).1fkm) https://app.strava.com/activities/%(id)d
    """

    realname = "https://github.com/lamby/stravabot"

    def signedOn(self):
        self.join(self.factory.channel)

        self.factory.club.callback = self.new_activity

    def new_activity(self, activity):
        athlete = '%(firstname)s %(lastname)s' % activity['athlete']

        activity['athlete'] = athlete.strip()
        activity['distance_km'] = activity['distance'] / 1000.

        txt = self.TEMPLATE.strip() % activity

        self.msg('#%s' % self.factory.channel, txt.encode('utf8'))

class LogBotFactory(protocol.ClientFactory):
    def __init__(self, channel, nickname, club_id, access_token, update_interval):
        self.channel = channel
        self.nickname = nickname

        self.club = StravaClub(club_id, access_token, update_interval)
        self.club.start()

    def buildProtocol(self, addr):
        p = LogBot()
        p.factory = self
        p.nickname = self.nickname

        return p

    def clientConnectionLost(self, connector, reason):
        connector.connect()

    def clientConnectionFailed(self, connector, reason):
        reactor.stop()

if __name__ == '__main__':
    server, port, nickname, channel, club_id, access_token, update_interval = sys.argv[1:]

    log.startLogging(sys.stdout)

    f = LogBotFactory(
        channel,
        nickname,
        club_id,
        access_token,
        int(update_interval),
    )

    reactor.connectTCP(server, int(port), f)
    reactor.run()
